// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: flick

#ifndef _FLICK_UI_H
#define _FLICK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_MenuScreen.h"
#include "screens/ui_JPKeyboardScreen.h"
#include "screens/ui_AtoZKeyboardScreen.h"
#include "screens/ui_DateAndTime.h"
#include "screens/ui_CursorScreen.h"
#include "screens/ui_AnalogClockWithBackgroud.h"
#include "screens/ui_SettingScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_760903683);    // assets/計算機のアイコン素材.png
LV_IMG_DECLARE(ui_img_637577056);    // assets/メーターアイコン9.png
LV_IMG_DECLARE(ui_img_1905819972);    // assets/電源ボタン (1).png
LV_IMG_DECLARE(ui_img_442148399);    // assets/照明のフリーアイコン2.png
LV_IMG_DECLARE(ui_img_717136436);    // assets/レンチ＆ドライバーの設定アイコン。.png
LV_IMG_DECLARE(ui_img_2026807732);    // assets/Uターン矢印 2.png
LV_IMG_DECLARE(ui_img_991498431);    // assets/バックスペースのアイコン素材 (1).png
LV_IMG_DECLARE(ui_img_171085870);    // assets/矢印アイコン　左2 (2).png
LV_IMG_DECLARE(ui_img_96606883);    // assets/シェア矢印アイコン (1).png
LV_IMG_DECLARE(ui_img_717184261);    // assets/pngegg (3).png

// FONTS
LV_FONT_DECLARE(ui_font_calc);
LV_FONT_DECLARE(ui_font_general);
LV_FONT_DECLARE(ui_font_general24);
LV_FONT_DECLARE(ui_font_JP);
LV_FONT_DECLARE(ui_font_NotoSerifJPEB32);
LV_FONT_DECLARE(ui_font_NotoSerifJPEB52);
LV_FONT_DECLARE(ui_font_SegmentDisplay128);
LV_FONT_DECLARE(ui_font_SegmentDisplay144);
LV_FONT_DECLARE(ui_font_SegmentDisplay160);
LV_FONT_DECLARE(ui_font_SegmentDisplay80);
LV_FONT_DECLARE(ui_font_SegmentDisplayl64);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
