// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: flick

#ifndef UI_ATOZKEYBOARDSCREEN_H
#define UI_ATOZKEYBOARDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AtoZKeyboardScreen
extern void ui_AtoZKeyboardScreen_screen_init(void);
extern void ui_AtoZKeyboardScreen_screen_destroy(void);
extern lv_obj_t * ui_AtoZKeyboardScreen;
extern lv_obj_t * ui_HeaderPanel1;
extern lv_obj_t * ui_TouchAndScrollPanel1;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_OtherKeyboard;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

