// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: flick

#include "../ui.h"

lv_obj_t * ui_AnalogClockWithBackgroud = NULL;
lv_obj_t * ui_Panel41 = NULL;
lv_obj_t * ui_AnalogClockContainer = NULL;
lv_obj_t * ui_DateHolder = NULL;
lv_obj_t * ui_Image11 = NULL;
// event funtions

// build funtions

void ui_AnalogClockWithBackgroud_screen_init(void)
{
    ui_AnalogClockWithBackgroud = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_AnalogClockWithBackgroud, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel41 = lv_obj_create(ui_AnalogClockWithBackgroud);
    lv_obj_set_width(ui_Panel41, lv_pct(100));
    lv_obj_set_height(ui_Panel41, lv_pct(100));
    lv_obj_set_align(ui_Panel41, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel41, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AnalogClockContainer = lv_obj_create(ui_Panel41);
    lv_obj_remove_style_all(ui_AnalogClockContainer);
    lv_obj_set_height(ui_AnalogClockContainer, 307);
    lv_obj_set_width(ui_AnalogClockContainer, lv_pct(70));
    lv_obj_set_x(ui_AnalogClockContainer, 43);
    lv_obj_set_y(ui_AnalogClockContainer, 214);
    lv_obj_set_align(ui_AnalogClockContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_AnalogClockContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_AnalogClockContainer, &ui_img_717184261, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateHolder = lv_label_create(ui_Panel41);
    lv_obj_set_width(ui_DateHolder, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateHolder, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateHolder, 120);
    lv_obj_set_y(ui_DateHolder, -146);
    lv_obj_set_align(ui_DateHolder, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateHolder, "2025/12/20 (Sat)  AM");
    lv_obj_set_style_text_font(ui_DateHolder, &ui_font_NotoSerifJPEB52, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_DateHolder, 900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image11 = lv_image_create(ui_AnalogClockWithBackgroud);
    lv_image_set_src(ui_Image11, &ui_img_2026807732);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image11, -111);
    lv_obj_set_y(ui_Image11, -311);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_rotation(ui_Image11, 900, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_AnalogClockWithBackgroud_screen_destroy(void)
{
    if(ui_AnalogClockWithBackgroud) lv_obj_del(ui_AnalogClockWithBackgroud);

    // NULL screen variables
    ui_AnalogClockWithBackgroud = NULL;
    ui_Panel41 = NULL;
    ui_AnalogClockContainer = NULL;
    ui_DateHolder = NULL;
    ui_Image11 = NULL;

}
