// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: flick

#include "../ui.h"

lv_obj_t * ui_AtoZKeyboardScreen = NULL;
lv_obj_t * ui_HeaderPanel1 = NULL;
lv_obj_t * ui_TouchAndScrollPanel1 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_OtherKeyboard = NULL;
// event funtions

// build funtions

void ui_AtoZKeyboardScreen_screen_init(void)
{
    ui_AtoZKeyboardScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_AtoZKeyboardScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeaderPanel1 = lv_obj_create(ui_AtoZKeyboardScreen);
    lv_obj_set_height(ui_HeaderPanel1, 80);
    lv_obj_set_width(ui_HeaderPanel1, lv_pct(100));
    lv_obj_set_x(ui_HeaderPanel1, 0);
    lv_obj_set_y(ui_HeaderPanel1, -360);
    lv_obj_set_align(ui_HeaderPanel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HeaderPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TouchAndScrollPanel1 = lv_obj_create(ui_AtoZKeyboardScreen);
    lv_obj_set_height(ui_TouchAndScrollPanel1, 370);
    lv_obj_set_width(ui_TouchAndScrollPanel1, lv_pct(100));
    lv_obj_set_x(ui_TouchAndScrollPanel1, 0);
    lv_obj_set_y(ui_TouchAndScrollPanel1, -135);
    lv_obj_set_align(ui_TouchAndScrollPanel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TouchAndScrollPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch2 = lv_switch_create(ui_TouchAndScrollPanel1);
    lv_obj_set_width(ui_Switch2, lv_pct(60));
    lv_obj_set_height(ui_Switch2, lv_pct(12));
    lv_obj_set_x(ui_Switch2, 0);
    lv_obj_set_y(ui_Switch2, 150);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    ui_OtherKeyboard = lv_keyboard_create(ui_AtoZKeyboardScreen);
    lv_obj_set_width(ui_OtherKeyboard, lv_pct(100));
    lv_obj_set_height(ui_OtherKeyboard, lv_pct(43));
    lv_obj_set_x(ui_OtherKeyboard, 0);
    lv_obj_set_y(ui_OtherKeyboard, 229);
    lv_obj_set_align(ui_OtherKeyboard, LV_ALIGN_CENTER);

    lv_obj_set_style_text_font(ui_OtherKeyboard, &lv_font_montserrat_24, LV_PART_ITEMS | LV_STATE_DEFAULT);

}

void ui_AtoZKeyboardScreen_screen_destroy(void)
{
    if(ui_AtoZKeyboardScreen) lv_obj_del(ui_AtoZKeyboardScreen);

    // NULL screen variables
    ui_AtoZKeyboardScreen = NULL;
    ui_HeaderPanel1 = NULL;
    ui_TouchAndScrollPanel1 = NULL;
    ui_Switch2 = NULL;
    ui_OtherKeyboard = NULL;

}
