// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: flick

#ifndef UI_ANALOGCLOCKWITHBACKGROUD_H
#define UI_ANALOGCLOCKWITHBACKGROUD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AnalogClockWithBackgroud
extern void ui_AnalogClockWithBackgroud_screen_init(void);
extern void ui_AnalogClockWithBackgroud_screen_destroy(void);
extern lv_obj_t * ui_AnalogClockWithBackgroud;
extern lv_obj_t * ui_Panel41;
extern lv_obj_t * ui_AnalogClockContainer;
extern lv_obj_t * ui_DateHolder;
extern lv_obj_t * ui_Image11;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

