// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: flick

#ifndef UI_CURSORSCREEN_H
#define UI_CURSORSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CursorScreen
extern void ui_CursorScreen_screen_init(void);
extern void ui_CursorScreen_screen_destroy(void);
extern lv_obj_t * ui_CursorScreen;
extern lv_obj_t * ui_HeaderPanel2;
extern lv_obj_t * ui_TouchAndScrollPanel2;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_JpFlickKeyboardPanel1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Panel24;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Panel25;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Panel26;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Panel27;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Panel28;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Panel29;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Panel30;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Panel31;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Panel32;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Panel33;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Panel34;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Panel35;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Panel36;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Panel37;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Panel38;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Panel39;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Panel40;
extern lv_obj_t * ui_Image10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

