// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: flick

#include "../ui.h"

lv_obj_t * ui_CursorScreen = NULL;
lv_obj_t * ui_HeaderPanel2 = NULL;
lv_obj_t * ui_TouchAndScrollPanel2 = NULL;
lv_obj_t * ui_Switch3 = NULL;
lv_obj_t * ui_JpFlickKeyboardPanel1 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Panel22 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_Panel23 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Panel24 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_Panel25 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Panel26 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Panel27 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Panel28 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Panel29 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Panel30 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Panel31 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Panel32 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Panel33 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Panel34 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Panel35 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Panel36 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Panel37 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Panel38 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Panel39 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Panel40 = NULL;
lv_obj_t * ui_Image10 = NULL;
// event funtions

// build funtions

void ui_CursorScreen_screen_init(void)
{
    ui_CursorScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_CursorScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeaderPanel2 = lv_obj_create(ui_CursorScreen);
    lv_obj_set_height(ui_HeaderPanel2, 80);
    lv_obj_set_width(ui_HeaderPanel2, lv_pct(100));
    lv_obj_set_x(ui_HeaderPanel2, 0);
    lv_obj_set_y(ui_HeaderPanel2, -360);
    lv_obj_set_align(ui_HeaderPanel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HeaderPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TouchAndScrollPanel2 = lv_obj_create(ui_CursorScreen);
    lv_obj_set_height(ui_TouchAndScrollPanel2, 370);
    lv_obj_set_width(ui_TouchAndScrollPanel2, lv_pct(100));
    lv_obj_set_x(ui_TouchAndScrollPanel2, 0);
    lv_obj_set_y(ui_TouchAndScrollPanel2, -135);
    lv_obj_set_align(ui_TouchAndScrollPanel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TouchAndScrollPanel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch3 = lv_switch_create(ui_TouchAndScrollPanel2);
    lv_obj_set_width(ui_Switch3, lv_pct(60));
    lv_obj_set_height(ui_Switch3, lv_pct(12));
    lv_obj_set_x(ui_Switch3, 0);
    lv_obj_set_y(ui_Switch3, 150);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);

    ui_JpFlickKeyboardPanel1 = lv_obj_create(ui_CursorScreen);
    lv_obj_set_width(ui_JpFlickKeyboardPanel1, lv_pct(100));
    lv_obj_set_height(ui_JpFlickKeyboardPanel1, lv_pct(43));
    lv_obj_set_x(ui_JpFlickKeyboardPanel1, 0);
    lv_obj_set_y(ui_JpFlickKeyboardPanel1, 229);
    lv_obj_set_align(ui_JpFlickKeyboardPanel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_JpFlickKeyboardPanel1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_JpFlickKeyboardPanel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_JpFlickKeyboardPanel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel1, 70);
    lv_obj_set_width(ui_Panel1, lv_pct(18));
    lv_obj_set_x(ui_Panel1, -162);
    lv_obj_set_y(ui_Panel1, 215);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_image_create(ui_Panel1);
    lv_image_set_src(ui_Image6, &ui_img_2026807732);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel22 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel22, 70);
    lv_obj_set_width(ui_Panel22, lv_pct(18));
    lv_obj_set_x(ui_Panel22, -162);
    lv_obj_set_y(ui_Panel22, 215);
    lv_obj_set_align(ui_Panel22, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel22, lv_color_hex(0x696969), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "ESC");
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel23 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel23, 70);
    lv_obj_set_width(ui_Panel23, lv_pct(18));
    lv_obj_set_x(ui_Panel23, -162);
    lv_obj_set_y(ui_Panel23, 215);
    lv_obj_set_align(ui_Panel23, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label17 = lv_label_create(ui_Panel23);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "paste");
    lv_obj_set_style_text_font(ui_Label17, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel24 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel24, 70);
    lv_obj_set_width(ui_Panel24, lv_pct(18));
    lv_obj_set_x(ui_Panel24, -162);
    lv_obj_set_y(ui_Panel24, 215);
    lv_obj_set_align(ui_Panel24, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label18 = lv_label_create(ui_Panel24);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Enter");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel25 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel25, 70);
    lv_obj_set_width(ui_Panel25, lv_pct(18));
    lv_obj_set_x(ui_Panel25, -162);
    lv_obj_set_y(ui_Panel25, 215);
    lv_obj_set_align(ui_Panel25, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_image_create(ui_Panel25);
    lv_image_set_src(ui_Image7, &ui_img_991498431);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel26 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel26, 70);
    lv_obj_set_width(ui_Panel26, lv_pct(18));
    lv_obj_set_x(ui_Panel26, -162);
    lv_obj_set_y(ui_Panel26, 215);
    lv_obj_set_align(ui_Panel26, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image8 = lv_image_create(ui_Panel26);
    lv_image_set_src(ui_Image8, &ui_img_171085870);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel27 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel27, 70);
    lv_obj_set_width(ui_Panel27, lv_pct(18));
    lv_obj_set_x(ui_Panel27, -162);
    lv_obj_set_y(ui_Panel27, 215);
    lv_obj_set_align(ui_Panel27, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label19 = lv_label_create(ui_Panel27);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Ctl+]");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel28 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel28, 70);
    lv_obj_set_width(ui_Panel28, lv_pct(18));
    lv_obj_set_x(ui_Panel28, -162);
    lv_obj_set_y(ui_Panel28, 215);
    lv_obj_set_align(ui_Panel28, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label20 = lv_label_create(ui_Panel28);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "copy");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel29 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel29, 70);
    lv_obj_set_width(ui_Panel29, lv_pct(18));
    lv_obj_set_x(ui_Panel29, -162);
    lv_obj_set_y(ui_Panel29, 215);
    lv_obj_set_align(ui_Panel29, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label21 = lv_label_create(ui_Panel29);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Redo");
    lv_obj_set_style_text_font(ui_Label21, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel30 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel30, 70);
    lv_obj_set_width(ui_Panel30, lv_pct(18));
    lv_obj_set_x(ui_Panel30, -162);
    lv_obj_set_y(ui_Panel30, 215);
    lv_obj_set_align(ui_Panel30, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image9 = lv_image_create(ui_Panel30);
    lv_image_set_src(ui_Image9, &ui_img_171085870);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image9, 1800);

    ui_Panel31 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel31, 70);
    lv_obj_set_width(ui_Panel31, lv_pct(18));
    lv_obj_set_x(ui_Panel31, -162);
    lv_obj_set_y(ui_Panel31, 215);
    lv_obj_set_align(ui_Panel31, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label22 = lv_label_create(ui_Panel31);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "?123");
    lv_obj_set_style_text_font(ui_Label22, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel32 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel32, 70);
    lv_obj_set_width(ui_Panel32, lv_pct(18));
    lv_obj_set_x(ui_Panel32, -162);
    lv_obj_set_y(ui_Panel32, 215);
    lv_obj_set_align(ui_Panel32, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label23 = lv_label_create(ui_Panel32);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "Shift");
    lv_obj_set_style_text_font(ui_Label23, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel33 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel33, 70);
    lv_obj_set_width(ui_Panel33, lv_pct(18));
    lv_obj_set_x(ui_Panel33, -162);
    lv_obj_set_y(ui_Panel33, 215);
    lv_obj_set_align(ui_Panel33, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel33, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image12 = lv_image_create(ui_Panel33);
    lv_image_set_src(ui_Image12, &ui_img_171085870);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image12, 900);

    ui_Panel34 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel34, 70);
    lv_obj_set_width(ui_Panel34, lv_pct(18));
    lv_obj_set_x(ui_Panel34, -162);
    lv_obj_set_y(ui_Panel34, 215);
    lv_obj_set_align(ui_Panel34, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel34, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label25 = lv_label_create(ui_Panel34);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "Undo");
    lv_obj_set_style_text_font(ui_Label25, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel35 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel35, 70);
    lv_obj_set_width(ui_Panel35, lv_pct(18));
    lv_obj_set_x(ui_Panel35, -162);
    lv_obj_set_y(ui_Panel35, 215);
    lv_obj_set_align(ui_Panel35, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label26 = lv_label_create(ui_Panel35);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "_");
    lv_obj_set_style_text_font(ui_Label26, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel36 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel36, 70);
    lv_obj_set_width(ui_Panel36, lv_pct(18));
    lv_obj_set_x(ui_Panel36, -162);
    lv_obj_set_y(ui_Panel36, 215);
    lv_obj_set_align(ui_Panel36, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel36, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_Panel36);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "あ/a");
    lv_obj_set_style_text_font(ui_Label27, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel37 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel37, 70);
    lv_obj_set_width(ui_Panel37, lv_pct(18));
    lv_obj_set_x(ui_Panel37, -162);
    lv_obj_set_y(ui_Panel37, 215);
    lv_obj_set_align(ui_Panel37, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image14 = lv_image_create(ui_Panel37);
    lv_image_set_src(ui_Image14, &ui_img_171085870);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel38 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel38, 70);
    lv_obj_set_width(ui_Panel38, lv_pct(18));
    lv_obj_set_x(ui_Panel38, -162);
    lv_obj_set_y(ui_Panel38, 215);
    lv_obj_set_align(ui_Panel38, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel38, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image13 = lv_image_create(ui_Panel38);
    lv_image_set_src(ui_Image13, &ui_img_171085870);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image13, 2700);

    ui_Panel39 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel39, 70);
    lv_obj_set_width(ui_Panel39, lv_pct(18));
    lv_obj_set_x(ui_Panel39, -162);
    lv_obj_set_y(ui_Panel39, 215);
    lv_obj_set_align(ui_Panel39, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel39, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image15 = lv_image_create(ui_Panel39);
    lv_image_set_src(ui_Image15, &ui_img_171085870);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image15, 1800);

    ui_Panel40 = lv_obj_create(ui_JpFlickKeyboardPanel1);
    lv_obj_set_height(ui_Panel40, 70);
    lv_obj_set_width(ui_Panel40, lv_pct(18));
    lv_obj_set_x(ui_Panel40, -162);
    lv_obj_set_y(ui_Panel40, 215);
    lv_obj_set_align(ui_Panel40, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel40, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image10 = lv_image_create(ui_Panel40);
    lv_image_set_src(ui_Image10, &ui_img_96606883);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_CursorScreen_screen_destroy(void)
{
    if(ui_CursorScreen) lv_obj_del(ui_CursorScreen);

    // NULL screen variables
    ui_CursorScreen = NULL;
    ui_HeaderPanel2 = NULL;
    ui_TouchAndScrollPanel2 = NULL;
    ui_Switch3 = NULL;
    ui_JpFlickKeyboardPanel1 = NULL;
    ui_Panel1 = NULL;
    ui_Image6 = NULL;
    ui_Panel22 = NULL;
    ui_Label16 = NULL;
    ui_Panel23 = NULL;
    ui_Label17 = NULL;
    ui_Panel24 = NULL;
    ui_Label18 = NULL;
    ui_Panel25 = NULL;
    ui_Image7 = NULL;
    ui_Panel26 = NULL;
    ui_Image8 = NULL;
    ui_Panel27 = NULL;
    ui_Label19 = NULL;
    ui_Panel28 = NULL;
    ui_Label20 = NULL;
    ui_Panel29 = NULL;
    ui_Label21 = NULL;
    ui_Panel30 = NULL;
    ui_Image9 = NULL;
    ui_Panel31 = NULL;
    ui_Label22 = NULL;
    ui_Panel32 = NULL;
    ui_Label23 = NULL;
    ui_Panel33 = NULL;
    ui_Image12 = NULL;
    ui_Panel34 = NULL;
    ui_Label25 = NULL;
    ui_Panel35 = NULL;
    ui_Label26 = NULL;
    ui_Panel36 = NULL;
    ui_Label27 = NULL;
    ui_Panel37 = NULL;
    ui_Image14 = NULL;
    ui_Panel38 = NULL;
    ui_Image13 = NULL;
    ui_Panel39 = NULL;
    ui_Image15 = NULL;
    ui_Panel40 = NULL;
    ui_Image10 = NULL;

}
