// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: flick

#include "../ui.h"

lv_obj_t * ui_DateAndTime = NULL;
lv_obj_t * ui_DateContainer = NULL;
lv_obj_t * ui_DateLabel = NULL;
lv_obj_t * ui_DateHoderLabel = NULL;
lv_obj_t * ui_TimeContainer = NULL;
lv_obj_t * ui_TimeLabel = NULL;
lv_obj_t * ui_TimeHolderLabel = NULL;
lv_obj_t * ui_TimeColonLabel = NULL;
lv_obj_t * ui_Back = NULL;
// event funtions

// build funtions

void ui_DateAndTime_screen_init(void)
{
    ui_DateAndTime = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_DateAndTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DateAndTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DateAndTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateContainer = lv_obj_create(ui_DateAndTime);
    lv_obj_remove_style_all(ui_DateContainer);
    lv_obj_set_height(ui_DateContainer, 120);
    lv_obj_set_width(ui_DateContainer, lv_pct(130));
    lv_obj_set_x(ui_DateContainer, 521);
    lv_obj_set_y(ui_DateContainer, -250);
    lv_obj_set_align(ui_DateContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DateContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_rotation(ui_DateContainer, 900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateLabel = lv_label_create(ui_DateContainer);
    lv_obj_set_width(ui_DateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateLabel, -247);
    lv_obj_set_y(ui_DateLabel, -31);
    lv_obj_set_align(ui_DateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateLabel, "現在日付");
    lv_obj_set_style_text_color(ui_DateLabel, lv_color_hex(0xFB8623), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateLabel, &ui_font_NotoSerifJPEB32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateHoderLabel = lv_label_create(ui_DateContainer);
    lv_obj_set_width(ui_DateHoderLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateHoderLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateHoderLabel, -3);
    lv_obj_set_y(ui_DateHoderLabel, 35);
    lv_obj_set_align(ui_DateHoderLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateHoderLabel, "2025/12/20 (SAT)");
    lv_obj_set_style_text_color(ui_DateHoderLabel, lv_color_hex(0xFB8623), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateHoderLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_DateHoderLabel, -10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_DateHoderLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DateHoderLabel, &ui_font_SegmentDisplay80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeContainer = lv_obj_create(ui_DateAndTime);
    lv_obj_remove_style_all(ui_TimeContainer);
    lv_obj_set_height(ui_TimeContainer, 250);
    lv_obj_set_width(ui_TimeContainer, lv_pct(125));
    lv_obj_set_x(ui_TimeContainer, 371);
    lv_obj_set_y(ui_TimeContainer, -177);
    lv_obj_set_align(ui_TimeContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TimeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_rotation(ui_TimeContainer, 900, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeLabel = lv_label_create(ui_TimeContainer);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeLabel, -190);
    lv_obj_set_y(ui_TimeLabel, -97);
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel, "現在時刻");
    lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0xFB8623), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeLabel, &ui_font_NotoSerifJPEB52, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeHolderLabel = lv_label_create(ui_TimeContainer);
    lv_obj_set_width(ui_TimeHolderLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeHolderLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeHolderLabel, 24);
    lv_obj_set_y(ui_TimeHolderLabel, 20);
    lv_obj_set_align(ui_TimeHolderLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeHolderLabel, "00 00 00");
    lv_obj_set_style_text_color(ui_TimeHolderLabel, lv_color_hex(0xFB8623), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeHolderLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TimeHolderLabel, -10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TimeHolderLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeHolderLabel, &ui_font_SegmentDisplay144, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_TimeHolderLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeColonLabel = lv_label_create(ui_TimeContainer);
    lv_obj_set_width(ui_TimeColonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeColonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeColonLabel, 13);
    lv_obj_set_y(ui_TimeColonLabel, -7);
    lv_obj_set_align(ui_TimeColonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeColonLabel, ":     :");
    lv_obj_set_style_text_color(ui_TimeColonLabel, lv_color_hex(0xFB8623), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeColonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_TimeColonLabel, -10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TimeColonLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeColonLabel, &ui_font_SegmentDisplay144, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Back = lv_label_create(ui_DateAndTime);
    lv_obj_set_width(ui_Back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Back, -99);
    lv_obj_set_y(ui_Back, -338);
    lv_obj_set_align(ui_Back, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Back, "戻る");
    lv_obj_set_style_text_color(ui_Back, lv_color_hex(0xFB8623), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Back, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Back, &ui_font_NotoSerifJPEB52, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_rotation(ui_Back, 900, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_DateAndTime_screen_destroy(void)
{
    if(ui_DateAndTime) lv_obj_del(ui_DateAndTime);

    // NULL screen variables
    ui_DateAndTime = NULL;
    ui_DateContainer = NULL;
    ui_DateLabel = NULL;
    ui_DateHoderLabel = NULL;
    ui_TimeContainer = NULL;
    ui_TimeLabel = NULL;
    ui_TimeHolderLabel = NULL;
    ui_TimeColonLabel = NULL;
    ui_Back = NULL;

}
