// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: flick

#ifndef UI_DATEANDTIME_H
#define UI_DATEANDTIME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DateAndTime
extern void ui_DateAndTime_screen_init(void);
extern void ui_DateAndTime_screen_destroy(void);
extern lv_obj_t * ui_DateAndTime;
extern lv_obj_t * ui_DateContainer;
extern lv_obj_t * ui_DateLabel;
extern lv_obj_t * ui_DateHoderLabel;
extern lv_obj_t * ui_TimeContainer;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_TimeHolderLabel;
extern lv_obj_t * ui_TimeColonLabel;
extern lv_obj_t * ui_Back;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

