// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: flick

#ifndef UI_JPKEYBOARDSCREEN_H
#define UI_JPKEYBOARDSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_JPKeyboardScreen
extern void ui_JPKeyboardScreen_screen_init(void);
extern void ui_JPKeyboardScreen_screen_destroy(void);
extern lv_obj_t * ui_JPKeyboardScreen;
extern lv_obj_t * ui_HeaderPanel;
extern lv_obj_t * ui_TouchAndScrollPanel;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_JpFlickKeyboardPanel;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Image5;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

