// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: flick

#include "../ui.h"

lv_obj_t * ui_JPKeyboardScreen = NULL;
lv_obj_t * ui_HeaderPanel = NULL;
lv_obj_t * ui_TouchAndScrollPanel = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_JpFlickKeyboardPanel = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Panel14 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Panel15 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Panel16 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Panel17 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Panel18 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Panel19 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Panel20 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Panel21 = NULL;
lv_obj_t * ui_Image5 = NULL;
// event funtions

// build funtions

void ui_JPKeyboardScreen_screen_init(void)
{
    ui_JPKeyboardScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_JPKeyboardScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeaderPanel = lv_obj_create(ui_JPKeyboardScreen);
    lv_obj_set_height(ui_HeaderPanel, 80);
    lv_obj_set_width(ui_HeaderPanel, lv_pct(100));
    lv_obj_set_x(ui_HeaderPanel, 0);
    lv_obj_set_y(ui_HeaderPanel, -360);
    lv_obj_set_align(ui_HeaderPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HeaderPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TouchAndScrollPanel = lv_obj_create(ui_JPKeyboardScreen);
    lv_obj_set_height(ui_TouchAndScrollPanel, 370);
    lv_obj_set_width(ui_TouchAndScrollPanel, lv_pct(100));
    lv_obj_set_x(ui_TouchAndScrollPanel, 0);
    lv_obj_set_y(ui_TouchAndScrollPanel, -135);
    lv_obj_set_align(ui_TouchAndScrollPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_TouchAndScrollPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Switch1 = lv_switch_create(ui_TouchAndScrollPanel);
    lv_obj_set_width(ui_Switch1, lv_pct(60));
    lv_obj_set_height(ui_Switch1, lv_pct(12));
    lv_obj_set_x(ui_Switch1, 0);
    lv_obj_set_y(ui_Switch1, 150);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_JpFlickKeyboardPanel = lv_obj_create(ui_JPKeyboardScreen);
    lv_obj_set_width(ui_JpFlickKeyboardPanel, lv_pct(100));
    lv_obj_set_height(ui_JpFlickKeyboardPanel, lv_pct(43));
    lv_obj_set_x(ui_JpFlickKeyboardPanel, 0);
    lv_obj_set_y(ui_JpFlickKeyboardPanel, 229);
    lv_obj_set_align(ui_JpFlickKeyboardPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_JpFlickKeyboardPanel, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_JpFlickKeyboardPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_JpFlickKeyboardPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel2, 70);
    lv_obj_set_width(ui_Panel2, lv_pct(18));
    lv_obj_set_x(ui_Panel2, -162);
    lv_obj_set_y(ui_Panel2, 215);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_image_create(ui_Panel2);
    lv_image_set_src(ui_Image2, &ui_img_2026807732);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel3, 70);
    lv_obj_set_width(ui_Panel3, lv_pct(18));
    lv_obj_set_x(ui_Panel3, -162);
    lv_obj_set_y(ui_Panel3, 215);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x696969), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "あ");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel4, 70);
    lv_obj_set_width(ui_Panel4, lv_pct(18));
    lv_obj_set_x(ui_Panel4, -162);
    lv_obj_set_y(ui_Panel4, 215);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "か");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel5, 70);
    lv_obj_set_width(ui_Panel5, lv_pct(18));
    lv_obj_set_x(ui_Panel5, -162);
    lv_obj_set_y(ui_Panel5, 215);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "さ");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel6, 70);
    lv_obj_set_width(ui_Panel6, lv_pct(18));
    lv_obj_set_x(ui_Panel6, -162);
    lv_obj_set_y(ui_Panel6, 215);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_image_create(ui_Panel6);
    lv_image_set_src(ui_Image3, &ui_img_991498431);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel7 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel7, 70);
    lv_obj_set_width(ui_Panel7, lv_pct(18));
    lv_obj_set_x(ui_Panel7, -162);
    lv_obj_set_y(ui_Panel7, 215);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_image_create(ui_Panel7);
    lv_image_set_src(ui_Image4, &ui_img_171085870);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel8 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel8, 70);
    lv_obj_set_width(ui_Panel8, lv_pct(18));
    lv_obj_set_x(ui_Panel8, -162);
    lv_obj_set_y(ui_Panel8, 215);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "た");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel9, 70);
    lv_obj_set_width(ui_Panel9, lv_pct(18));
    lv_obj_set_x(ui_Panel9, -162);
    lv_obj_set_y(ui_Panel9, 215);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Panel9);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "な");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel10, 70);
    lv_obj_set_width(ui_Panel10, lv_pct(18));
    lv_obj_set_x(ui_Panel10, -162);
    lv_obj_set_y(ui_Panel10, 215);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "は");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel11, 70);
    lv_obj_set_width(ui_Panel11, lv_pct(18));
    lv_obj_set_x(ui_Panel11, -162);
    lv_obj_set_y(ui_Panel11, 215);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_image_create(ui_Panel11);
    lv_image_set_src(ui_Image1, &ui_img_171085870);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image1, 1800);

    ui_Panel12 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel12, 70);
    lv_obj_set_width(ui_Panel12, lv_pct(18));
    lv_obj_set_x(ui_Panel12, -162);
    lv_obj_set_y(ui_Panel12, 215);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "?123");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel13 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel13, 70);
    lv_obj_set_width(ui_Panel13, lv_pct(18));
    lv_obj_set_x(ui_Panel13, -162);
    lv_obj_set_y(ui_Panel13, 215);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "ま");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel14 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel14, 70);
    lv_obj_set_width(ui_Panel14, lv_pct(18));
    lv_obj_set_x(ui_Panel14, -162);
    lv_obj_set_y(ui_Panel14, 215);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "や");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel15 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel15, 70);
    lv_obj_set_width(ui_Panel15, lv_pct(18));
    lv_obj_set_x(ui_Panel15, -162);
    lv_obj_set_y(ui_Panel15, 215);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Panel15);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "ら");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel16, 70);
    lv_obj_set_width(ui_Panel16, lv_pct(18));
    lv_obj_set_x(ui_Panel16, -162);
    lv_obj_set_y(ui_Panel16, 215);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_Panel16);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "_");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel17 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel17, 70);
    lv_obj_set_width(ui_Panel17, lv_pct(18));
    lv_obj_set_x(ui_Panel17, -162);
    lv_obj_set_y(ui_Panel17, 215);
    lv_obj_set_align(ui_Panel17, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label12 = lv_label_create(ui_Panel17);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "あ/a");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel18 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel18, 70);
    lv_obj_set_width(ui_Panel18, lv_pct(18));
    lv_obj_set_x(ui_Panel18, -162);
    lv_obj_set_y(ui_Panel18, 215);
    lv_obj_set_align(ui_Panel18, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_Panel18);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "\"o");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel19 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel19, 70);
    lv_obj_set_width(ui_Panel19, lv_pct(18));
    lv_obj_set_x(ui_Panel19, -162);
    lv_obj_set_y(ui_Panel19, 215);
    lv_obj_set_align(ui_Panel19, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label14 = lv_label_create(ui_Panel19);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "わ");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel20 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel20, 70);
    lv_obj_set_width(ui_Panel20, lv_pct(18));
    lv_obj_set_x(ui_Panel20, -162);
    lv_obj_set_y(ui_Panel20, 215);
    lv_obj_set_align(ui_Panel20, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label15 = lv_label_create(ui_Panel20);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "     ?\n。、!");
    lv_obj_set_style_text_font(ui_Label15, &ui_font_general24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel21 = lv_obj_create(ui_JpFlickKeyboardPanel);
    lv_obj_set_height(ui_Panel21, 70);
    lv_obj_set_width(ui_Panel21, lv_pct(18));
    lv_obj_set_x(ui_Panel21, -162);
    lv_obj_set_y(ui_Panel21, 215);
    lv_obj_set_align(ui_Panel21, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_image_create(ui_Panel21);
    lv_image_set_src(ui_Image5, &ui_img_96606883);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_JPKeyboardScreen_screen_destroy(void)
{
    if(ui_JPKeyboardScreen) lv_obj_del(ui_JPKeyboardScreen);

    // NULL screen variables
    ui_JPKeyboardScreen = NULL;
    ui_HeaderPanel = NULL;
    ui_TouchAndScrollPanel = NULL;
    ui_Switch1 = NULL;
    ui_JpFlickKeyboardPanel = NULL;
    ui_Panel2 = NULL;
    ui_Image2 = NULL;
    ui_Panel3 = NULL;
    ui_Label2 = NULL;
    ui_Panel4 = NULL;
    ui_Label1 = NULL;
    ui_Panel5 = NULL;
    ui_Label3 = NULL;
    ui_Panel6 = NULL;
    ui_Image3 = NULL;
    ui_Panel7 = NULL;
    ui_Image4 = NULL;
    ui_Panel8 = NULL;
    ui_Label4 = NULL;
    ui_Panel9 = NULL;
    ui_Label5 = NULL;
    ui_Panel10 = NULL;
    ui_Label6 = NULL;
    ui_Panel11 = NULL;
    ui_Image1 = NULL;
    ui_Panel12 = NULL;
    ui_Label7 = NULL;
    ui_Panel13 = NULL;
    ui_Label8 = NULL;
    ui_Panel14 = NULL;
    ui_Label9 = NULL;
    ui_Panel15 = NULL;
    ui_Label10 = NULL;
    ui_Panel16 = NULL;
    ui_Label11 = NULL;
    ui_Panel17 = NULL;
    ui_Label12 = NULL;
    ui_Panel18 = NULL;
    ui_Label13 = NULL;
    ui_Panel19 = NULL;
    ui_Label14 = NULL;
    ui_Panel20 = NULL;
    ui_Label15 = NULL;
    ui_Panel21 = NULL;
    ui_Image5 = NULL;

}
