// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: flick

#include "../ui.h"

lv_obj_t * ui_MenuScreen = NULL;
lv_obj_t * ui_HeaderPanel4 = NULL;
lv_obj_t * ui_DateHolderLabel = NULL;
lv_obj_t * ui_TimeHolder = NULL;
lv_obj_t * ui_BatteryBar = NULL;
lv_obj_t * ui_Panel42 = NULL;
lv_obj_t * ui_KeyBoards = NULL;
lv_obj_t * ui_Clock = NULL;
lv_obj_t * ui_PowerOnPC = NULL;
lv_obj_t * ui_LightOn = NULL;
lv_obj_t * ui_Setthing = NULL;
// event funtions

// build funtions

void ui_MenuScreen_screen_init(void)
{
    ui_MenuScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MenuScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeaderPanel4 = lv_obj_create(ui_MenuScreen);
    lv_obj_set_height(ui_HeaderPanel4, 80);
    lv_obj_set_width(ui_HeaderPanel4, lv_pct(100));
    lv_obj_set_x(ui_HeaderPanel4, 0);
    lv_obj_set_y(ui_HeaderPanel4, -360);
    lv_obj_set_align(ui_HeaderPanel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HeaderPanel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DateHolderLabel = lv_label_create(ui_HeaderPanel4);
    lv_obj_set_width(ui_DateHolderLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateHolderLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateHolderLabel, -118);
    lv_obj_set_y(ui_DateHolderLabel, 0);
    lv_obj_set_align(ui_DateHolderLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateHolderLabel, "YYYY/MM/dd (Sat)");
    lv_obj_set_style_text_font(ui_DateHolderLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeHolder = lv_label_create(ui_HeaderPanel4);
    lv_obj_set_width(ui_TimeHolder, 64);
    lv_obj_set_height(ui_TimeHolder, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeHolder, 69);
    lv_obj_set_y(ui_TimeHolder, 2);
    lv_obj_set_align(ui_TimeHolder, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeHolder, "24:00");
    lv_obj_set_style_text_font(ui_TimeHolder, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryBar = lv_bar_create(ui_HeaderPanel4);
    lv_bar_set_value(ui_BatteryBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBar, 80);
    lv_obj_set_height(ui_BatteryBar, 41);
    lv_obj_set_x(ui_BatteryBar, 183);
    lv_obj_set_y(ui_BatteryBar, -1);
    lv_obj_set_align(ui_BatteryBar, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_BatteryBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_BatteryBar,
                                                                                                 lv_obj_get_style_pad_right(ui_BatteryBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Panel42 = lv_obj_create(ui_MenuScreen);
    lv_obj_set_height(ui_Panel42, 725);
    lv_obj_set_width(ui_Panel42, lv_pct(100));
    lv_obj_set_x(ui_Panel42, -4);
    lv_obj_set_y(ui_Panel42, 39);
    lv_obj_set_align(ui_Panel42, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel42, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel42, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Panel42, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_KeyBoards = lv_obj_create(ui_Panel42);
    lv_obj_set_width(ui_KeyBoards, lv_pct(49));
    lv_obj_set_height(ui_KeyBoards, lv_pct(32));
    lv_obj_set_align(ui_KeyBoards, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_KeyBoards, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_KeyBoards, &ui_img_760903683, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Clock = lv_obj_create(ui_Panel42);
    lv_obj_set_width(ui_Clock, lv_pct(49));
    lv_obj_set_height(ui_Clock, lv_pct(32));
    lv_obj_set_align(ui_Clock, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Clock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Clock, &ui_img_637577056, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerOnPC = lv_obj_create(ui_Panel42);
    lv_obj_set_width(ui_PowerOnPC, lv_pct(49));
    lv_obj_set_height(ui_PowerOnPC, lv_pct(32));
    lv_obj_set_align(ui_PowerOnPC, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PowerOnPC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_PowerOnPC, &ui_img_1905819972, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightOn = lv_obj_create(ui_Panel42);
    lv_obj_set_width(ui_LightOn, lv_pct(49));
    lv_obj_set_height(ui_LightOn, lv_pct(32));
    lv_obj_set_align(ui_LightOn, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LightOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_LightOn, &ui_img_442148399, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Setthing = lv_obj_create(ui_Panel42);
    lv_obj_set_width(ui_Setthing, lv_pct(49));
    lv_obj_set_height(ui_Setthing, lv_pct(32));
    lv_obj_set_align(ui_Setthing, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Setthing, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Setthing, &ui_img_717136436, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_MenuScreen_screen_destroy(void)
{
    if(ui_MenuScreen) lv_obj_del(ui_MenuScreen);

    // NULL screen variables
    ui_MenuScreen = NULL;
    ui_HeaderPanel4 = NULL;
    ui_DateHolderLabel = NULL;
    ui_TimeHolder = NULL;
    ui_BatteryBar = NULL;
    ui_Panel42 = NULL;
    ui_KeyBoards = NULL;
    ui_Clock = NULL;
    ui_PowerOnPC = NULL;
    ui_LightOn = NULL;
    ui_Setthing = NULL;

}
