// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: flick

#ifndef UI_MENUSCREEN_H
#define UI_MENUSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MenuScreen
extern void ui_MenuScreen_screen_init(void);
extern void ui_MenuScreen_screen_destroy(void);
extern lv_obj_t * ui_MenuScreen;
extern lv_obj_t * ui_HeaderPanel4;
extern lv_obj_t * ui_DateHolderLabel;
extern lv_obj_t * ui_TimeHolder;
extern lv_obj_t * ui_BatteryBar;
extern lv_obj_t * ui_Panel42;
extern lv_obj_t * ui_KeyBoards;
extern lv_obj_t * ui_Clock;
extern lv_obj_t * ui_PowerOnPC;
extern lv_obj_t * ui_LightOn;
extern lv_obj_t * ui_Setthing;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

