// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: flick

#ifndef UI_SETTINGSCREEN_H
#define UI_SETTINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingScreen
extern void ui_SettingScreen_screen_init(void);
extern void ui_SettingScreen_screen_destroy(void);
extern lv_obj_t * ui_SettingScreen;
extern lv_obj_t * ui_HeaderPanel3;
extern lv_obj_t * ui_DateHolderLabel1;
extern lv_obj_t * ui_TimeHolder1;
extern lv_obj_t * ui_BatteryBar1;
extern lv_obj_t * ui_Panel43;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

