// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: flick

#include "../ui.h"

lv_obj_t * ui_SettingScreen = NULL;
lv_obj_t * ui_HeaderPanel3 = NULL;
lv_obj_t * ui_DateHolderLabel1 = NULL;
lv_obj_t * ui_TimeHolder1 = NULL;
lv_obj_t * ui_BatteryBar1 = NULL;
lv_obj_t * ui_Panel43 = NULL;
// event funtions

// build funtions

void ui_SettingScreen_screen_init(void)
{
    ui_SettingScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SettingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeaderPanel3 = lv_obj_create(ui_SettingScreen);
    lv_obj_set_height(ui_HeaderPanel3, 80);
    lv_obj_set_width(ui_HeaderPanel3, lv_pct(100));
    lv_obj_set_x(ui_HeaderPanel3, 0);
    lv_obj_set_y(ui_HeaderPanel3, -360);
    lv_obj_set_align(ui_HeaderPanel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HeaderPanel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DateHolderLabel1 = lv_label_create(ui_HeaderPanel3);
    lv_obj_set_width(ui_DateHolderLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateHolderLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateHolderLabel1, -118);
    lv_obj_set_y(ui_DateHolderLabel1, 0);
    lv_obj_set_align(ui_DateHolderLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateHolderLabel1, "YYYY/MM/dd (Sat)");
    lv_obj_set_style_text_font(ui_DateHolderLabel1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeHolder1 = lv_label_create(ui_HeaderPanel3);
    lv_obj_set_width(ui_TimeHolder1, 64);
    lv_obj_set_height(ui_TimeHolder1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeHolder1, 69);
    lv_obj_set_y(ui_TimeHolder1, 2);
    lv_obj_set_align(ui_TimeHolder1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeHolder1, "24:00");
    lv_obj_set_style_text_font(ui_TimeHolder1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryBar1 = lv_bar_create(ui_HeaderPanel3);
    lv_bar_set_value(ui_BatteryBar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBar1, 80);
    lv_obj_set_height(ui_BatteryBar1, 41);
    lv_obj_set_x(ui_BatteryBar1, 183);
    lv_obj_set_y(ui_BatteryBar1, -1);
    lv_obj_set_align(ui_BatteryBar1, LV_ALIGN_CENTER);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_BatteryBar1, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_BatteryBar1,
                                                                                                  lv_obj_get_style_pad_right(ui_BatteryBar1, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Panel43 = lv_obj_create(ui_SettingScreen);
    lv_obj_set_height(ui_Panel43, 725);
    lv_obj_set_width(ui_Panel43, lv_pct(100));
    lv_obj_set_x(ui_Panel43, -4);
    lv_obj_set_y(ui_Panel43, 39);
    lv_obj_set_align(ui_Panel43, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel43, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel43, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Panel43, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_SettingScreen_screen_destroy(void)
{
    if(ui_SettingScreen) lv_obj_del(ui_SettingScreen);

    // NULL screen variables
    ui_SettingScreen = NULL;
    ui_HeaderPanel3 = NULL;
    ui_DateHolderLabel1 = NULL;
    ui_TimeHolder1 = NULL;
    ui_BatteryBar1 = NULL;
    ui_Panel43 = NULL;

}
